theme: jekyll-theme-chirpy

lang: en

title: Runex

tagline: Documentation and reference page # it will display as the subtitle

description: >- # used by seo meta and the atom feed
  Documentation for Runex - a tool to generate a project prompt following Git's .gitignore rules.

baseurl: "/runex"
url: "https://bluejay909.github.io"


github:
  username: BlueJay909

theme_mode: dark
cdn: "https://chirpy-img.netlify.app"

nav:
  - title: Readme
    url: "{{ '/README.html' | relative_url }}"
  - title: CLI Usage
    url: "{{ '/cli.html' | relative_url }}"
  - title: Core Module
    url: "{{ '/core.html' | relative_url }}"
  - title: Ignore Logic
    url: "{{ '/ignore_logic.html' | relative_url }}"
  - title: Wildmatch Logic
    url: "{{ '/wildmatch.html' | relative_url }}"
